### ISSUE TITLE
Merge Upstream PRs

### ISSUE THREAD

**Issue by Petersoj** [ekristen/aws-nuke#135]
Thanks for your work on this fork and maintaining `aws-nuke`! I noticed that there are several forks in the original project repo ([like this one](https://github.com/rebuy-de/aws-nuke/pull/1152)) that might be a good idea to merge (manually) into this fork. Any plans to do this?

**Comment by ekristen** [comment]
Yes absolutely. I usually review every couple of weeks and I have it semi-automated to pull it in. Looks like I hadn't seen that on. 

I plan on jumping out of beta soon, I haven't found any new issues recently. Let me know if you do.

If you want to open an issue for a candidate PR to bring it to my attention that would be great. I'll look at pulling that one over. I try and keep commit history when possible, that one looks a little messy, so I might have to do some squashing, we'll see.

**Comment by Petersoj** [comment]
Wow that was insanely fast. You are a rockstar! Thanks!

**Comment by ekristen** [comment]
Please give it a go and let me know if you run into any issues. I didn't have any cloud front policies to directly test it against.

**Comment by ekristen** [comment]
Truthfully your issue caught me at a good time, I can't promise to always be this fast, but my goal is to not let things dwindle.

**Comment by ekristen** [comment]
@Petersoj I actually found 2 minor issues I need to fix, PR inbound shortly.

**Comment by Petersoj** [comment]
I will test it out soon! Thanks again.
