### ISSUE TITLE
[Idea] Delete EC2 Instance `Name` Tags On Termination

### ISSUE THREAD

**Issue by Petersoj** [ekristen/aws-nuke#138]
When an EC2 instance is terminated, the instance stays in the terminated state for about an hour, then it disappears from the AWS account. The problem with this is that once `aws-nuke` finishes by terminating all EC2 instances in the AWS account, the EC2 instances are still leftover in the account. So if subsequent infrastructure migrations create EC2 instances with names (using the `Name` tag), then the migrations could run into issues because there are now multiple EC2 instances with the same name. For example, a running instance and a terminated instance both with the `Name` tag value of "webserver". So it might be a good idea if `aws-nuke` deletes the tags of all EC2 instances before terminating them.

**Comment by ekristen** [comment]
I've run into this in the past, I think it's just the `Name` tag that causes the conflict. Removing all the tags would be the easiest approach, I don't immediately see a downside to this approach.

**Comment by Petersoj** [comment]
Yeah I imagine removing all the tags on an EC2 instance would fix this issue and not cause any unintended issues.
PR for it: #139

**Comment by ekristen** [comment]
hey @Petersoj thanks for your PR, sounds like I need to write up some documentation on how to edit your previous commits so you don't have to close out and re-open, you can always edit and force push to make changes like signing or message syntax.

**Comment by Petersoj** [comment]
Yeah I was considering force pushing, but I was reading up on how that isn't the best practice in most cases. Perhaps it was permissible in this case though.

**Comment by ekristen** [comment]
@Petersoj when you are working on a PR it's fine generally speaking. You just don't want to be doing force pushes on primary branches/release branches, etc where others are working or where the history is at, when it comes to a new feature and doing a PR, force pushes are normal, because you might amend commits or rebase of the current main branch to make sure you are up to date or to resolve conflicts, etc.
