### ISSUE TITLE
Add support for SageMaker Space Apps and Spaces

### ISSUE THREAD

**Issue by npellegrin** [ekristen/aws-nuke#157]
In rebuy.de/aws-nuke the current SageMakerApp implementation doesn't support deleting apps with a SpaceName. Also, SageMaker Spaces are not currently supported.

This issue duplicates https://github.com/rebuy-de/aws-nuke/issues/1184 to implement the feature in ekristen/aws-nuke

**Comment by npellegrin** [comment]
Thanks for the migrate tool! Will try it with my next contributions 😃

Agree on unit tests, I will implement some with my other PR because it is hard to test Bedrock stuff on real infrastructure without giving a lot of money to AWS.

**Comment by ekristen** [comment]
Indeed, probably why they haven't been added before. Do you occasionally have bedrock resources that need cleaned up or just trying to be proactive? Ideally we should get some real world usage before getting it in, but if we can get some decent mocks in place I'm ok with that too.

**Comment by npellegrin** [comment]
I have some bedrock resources to remove occasionally. In particular, last week a provisioned throughput for Bedrock earned AWS $400 in 24 hours before we noticed 😭 

I'll be able to test this PR with a real infrastructure, at least once to validate everything is properly deleted, but I'll start with mocks it will be easier.
