### ISSUE TITLE
feature: add bypass prod string in alias check

### ISSUE THREAD

**Issue by ekristen** [ekristen/aws-nuke#174]
There are a few options here.

1. allow overriding all "strings" that are in the alias, i.e. people might use `live` vs `prod` and might want to prevent running against those.
2. allow bypassing this check, possibly implement like bypass alias check https://ekristen.github.io/aws-nuke/features/bypass-alias-check/

**Comment by ekristen** [comment]
Hi @jasonwbarnett I'm pinging you here because I'm managing a breakaway fork that I've been rewriting and updating to make it easier for contributions. I'm doubtful that https://github.com/rebuy-de/aws-nuke/pull/1224 will get merged. It's happened before, but I'm open to implementing on this version of aws-nuke. 

I have a feature for bypassing alias checks. I think I would want to implement it similar. Require the account ID to be in a configuration block, and pass a CLI flag, that way it makes it a conscious choice not something likely done on accident.

**Comment by ekristen** [comment]
@jasonwbarnett I was reviewing the code this weekend and the bypass alias check feature I already added will allow you to bypass the prod substring check as well, although I wonder if this shouldn't be a separate feature.

**Comment by jasonwbarnett** [comment]
In what PR was this completed?

**Comment by ekristen** [comment]
@jasonwbarnett at the moment this feature currently allows for bypassing anything alias related including strings like `prod` https://ekristen.github.io/aws-nuke/features/bypass-alias-check/ 

This feature allows you to bypass all alias checks by configuring the account in the yaml and by providing a cli switch.

If you are interested in having a custom list of strings to block for the alias please let me know and we can open an issue to track that.
