### ISSUE TITLE
SIGSEGV error

### ISSUE THREAD

**Issue by Petersoj** [ekristen/aws-nuke#199]
Getting a SIGSEGV error when `aws-nuke` is printing resource IDs before nuke confirmation in version `3.2.0`. See stacktrace:
<img width="1091" alt="Screenshot 2024-06-21 at 3 18 59 PM copy" src="https://github.com/ekristen/aws-nuke/assets/14127217/312fecfc-9530-4a77-bca8-003d63e94ddd">

**Comment by ekristen** [comment]
Well that's not what you want to see. Let me take a look.

**Comment by ekristen** [comment]
@Petersoj I see the problem. I'll get patch up here shortly.

**Comment by ekristen** [comment]
@Petersoj what OS are you on? I'll cut you a build for testing.

**Comment by Petersoj** [comment]
@ekristen I'm using Docker on macOS ARM.

**Comment by ekristen** [comment]
I was able to duplicate. Just working on getting the fix in fully now.

**Comment by ekristen** [comment]
Time between release cut and builds can be about 5-10 minutes, give it a few and it'll show up with all the artifacts and docker images.

**Comment by Petersoj** [comment]
Excellent! The patch release works great. Thank you!
