### ISSUE TITLE
Missing KMS alias - Alias pagination

### ISSUE THREAD

**Issue by vinhltr** [ekristen/aws-nuke#205]
thanks for creating this fork, I've just found out about this today while trying to find ways to deal with existing bugs of the old nuke repo.

I'm having an issue with KMS alias. It does not seem to list all existing aliases (e.g missing redis, etc), even though my config does not filter them out. I suspect there are paginations on the list function that haven't been accounted for. There is an MR in the old repo which seems to try to tackle the problem, https://github.com/rebuy-de/aws-nuke/pull/1113/files

**Comment by ekristen** [comment]
Thanks for the report, I will take a look.
