### ISSUE TITLE
Skip `would-remove`?

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#230]
Question: When aws-nuke is running with the flag `--no-dry-run true` is there a way to skip the phase where it just tells you what it "would remove: and goes directly to removal?

The reason is - we run a script that assumes role in the target account to perform nuking there, and you can only assume the role for 1 hour. And really cluttered accounts take long time to process.

**Comment by ekristen** [comment]
No because it had to discover all the things it needs to remove first and that's really core functionality at this time.

You can adjust the duration an STS token is available for.

**Comment by YuriGal** [comment]
Unfortunately we're running the script with nuke inside of a CodeBuild, and it's the CodeBuild Role that assumes the role in target account. With role chaining maximum allowed session duration is 1 hour.

Thanks! We will try to figure something out on our side.

**Comment by ekristen** [comment]
With that in mind it's possible we could improve the AWS auth to re-assume role if it expires in an update.

Are you using the assume role options on the cli?

**Comment by YuriGal** [comment]
I don't recall exactly why, but we're not using assume role option, so currently we're doing it via CLI. But will gladly switch to the nuke options if it can offer extended session.

**Comment by ekristen** [comment]
If you wanna walk me through your authentication model. I can help with some suggestions.

**Comment by YuriGal** [comment]
Sure, thanks! It's pretty straightforward, here's that part from the codebuild specs:

```
          build: {
            commands: [
              'echo "Running AWS Nuke"',
              `ASSUMED_ROLE=$(aws sts assume-role --role-arn "arn:aws:iam::\${ACCOUNT_ID}:role/${props.roleName}" --role-session-name "NukeSession" --region=us-east-1)`,
              `export AWS_ACCESS_KEY_ID=$(echo $ASSUMED_ROLE | jq -r .Credentials.AccessKeyId)`,
              `export AWS_SECRET_ACCESS_KEY=$(echo $ASSUMED_ROLE | jq -r .Credentials.SecretAccessKey)`,
              `export AWS_SESSION_TOKEN=$(echo $ASSUMED_ROLE | jq -r .Credentials.SessionToken)`,
              `if [ "$IS_DRY_RUN" = "false" ]; then FLAGS="--no-dry-run"; fi`,
              `timeout ${
                // stop nuke 5 minutes before assumed role session timeout
                ROLE_SESSION_TIMEOUT - 5
              }m aws-nuke run --config nuke-config.yml --quiet --no-prompt --prompt-delay 3 --max-wait-retries ${MAX_RETRIES} $FLAGS`,
            ],
          },
```

**Comment by ekristen** [comment]
The following cli options are available ..

```
--assume-role-arn value                                                                  the role arn to assume using the credentials provided in the profile or statically set [$AWS_ASSUME_ROLE_ARN]
   --assume-role-session-name value                                                         the session name to provide for the assumed role [$AWS_ASSUME_ROLE_SESSION_NAME]
   --assume-role-external-id value                                                          the external id to provide for the assumed role [$AWS_ASSUME_ROLE_EXTERNAL_ID]
```

technically you could forgo the sts call and the export and provide them directly to aws-nuke, but that won't help with the 1 hour issue at the moment. However in the future I could make it that if `--assume-role` is being used then it could automatically renew during run if it's getting close to the 1 hour mark.

**Comment by YuriGal** [comment]
Yes, for now we can come up with some scripting solution (catch the error, and it it's a timeout - reassume the role etc.)

In the above options I am not clear about the external ID one - is it required? From what I read about it it's an ID given to you by the admin of the account you assume role in for additional security, but we don't do this.

**Comment by ekristen** [comment]
Session name and external name are optional

**Comment by yakirch** [comment]
@ekristen Thank you for your efforts to enhance this project. I'm currently encountering an issue when using a CodeBuild project to assume a role in the target account where I'm running AWS Nuke. In some accounts, the initial stage takes a significant amount of time, and by the time it attempts to delete resources, we receive an ExpiredTokenException error due to the 1-hour role chaining limit on assumed roles. You can refer to the limitation details [here](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#API_AssumeRole_RequestParameters).

**Comment by ekristen** [comment]
We can't skip and we can't change the assume role rules unfortunately. However I do have an feature wanting feedback. https://github.com/ekristen/aws-nuke/issues/85
