### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#238]
Sorry to bring another issue 😅 it looks like I will be your testing ground. 

Noticed another error in nuke dry run today:

> time="2024-07-30T12:41:31Z" level=error msg="Listing SecretsManagerSecret failed:\n    runtime error: invalid memory address or nil pointer dereference\n\n    goroutine 4283 [running]:\n    runtime/debug.Stack()\n    \truntime/debug/stack.go:24 +0x5e\n    github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list.func1()\n    \tgithub.com/ekristen/libnuke@v0.17.1/pkg/scanner/scanner.go:108 +0x72\n    panic({0x521a3e0?, 0xa6b0a30?})\n    \truntime/panic.go:914 +0x21f\n    github.com/ekristen/aws-nuke/v3/resources.(*SecretsManagerSecretLister).List(0x5386720?, {0xc0001105d0?, 0x638cff6?}, {0x4798ec0?, 0xc0004e4b90})\n    \tgithub.com/ekristen/aws-nuke/v3/resources/secretsmanager-secret.go:50 +0x203\n    github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000196420, {0x6be9358?, 0xc000100fa0?}, {0xc0000da3a0, 0x9}, {0x638cff6, 0x14}, {0x4798ec0?, 0xc0004e4b90})\n    \tgithub.com/ekristen/libnuke@v0.17.1/pkg/scanner/scanner.go:124 +0x193\n    created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1\n    \tgithub.com/ekristen/libnuke@v0.17.1/pkg/scanner/scanner.go:89 +0x4b\n"

**Comment by ekristen** [comment]
What version of aws-nuke are you running?

**Comment by YuriGal** [comment]
We're currently on `v3.2.2`

**Comment by ekristen** [comment]
Lots of fixes since then. Fairly certain it's already been addressed. That stack trace doesn't align with current code. Pretty sure that was fixed in https://github.com/ekristen/aws-nuke/releases/tag/v3.3.1

**Comment by YuriGal** [comment]
Will do thanks!
