### ISSUE TITLE
CloudWatchLogsLogGroup Rate Limit Exceeded

### ISSUE THREAD

**Issue by ekristen** [ekristen/aws-nuke#239]
This account has 13317 log groups. And yes, the "ThrottlingException: Rate exceeded" consistently happen during "Listing CloudWatchLogsLogGroup" even if I target log groups exclusively.

_Originally posted by @YuriGal in https://github.com/ekristen/aws-nuke/issues/237#issuecomment-2258284443_

**Comment by YuriGal** [comment]
Thanks! Will test this today.

**Comment by YuriGal** [comment]
It's working!

![image](https://github.com/user-attachments/assets/efbb7f25-4503-4823-ba96-90e84c8e7ade)

**Comment by ekristen** [comment]
Great. I was fairly certain it would, just didn't have a good way to test it.
