### ISSUE TITLE
Budget not filtered on global tags

### ISSUE THREAD

**Issue by mdgm88** [ekristen/aws-nuke#278]
I have set a global filter to not remove any resource with given tags, but these are ignored for the Budget resource

**Comment by ekristen** [comment]
Budgets don't currently support tags, that's why it's not working.

**Comment by mdgm88** [comment]
Budgets do support tags in the AWS SDK. See e.g. https://github.com/aws/aws-sdk-go/releases/tag/v1.52.4

**Comment by ekristen** [comment]
I meant in the tool they aren't implemented. I'm pretty busy this weekend but I'll look at it as soon as I can.
