### ISSUE TITLE
IAM Role, missing Path property

### ISSUE THREAD

**Issue by mdgm88** [ekristen/aws-nuke#279]
It looks like at least some of the changes from https://github.com/rebuy-de/aws-nuke/pull/914 are missing, especially for iam-roles.go

I would like to exclude roles in particular paths from being deleted.

**Comment by ekristen** [comment]
Interesting. I'll take a look. Things diverged back in December, I thought I had captured all the changes since, but might have missed something.

**Comment by mdgm88** [comment]
It might just be for iam-roles.go. Especially in https://github.com/ekristen/aws-nuke/blob/main/resources/iam-roles.go#L67C1-L73C5

The properties for the Name, Path etc. for the role are missing that were added in the PR mentioned above.

**Comment by ekristen** [comment]
Weird. Not sure how that happened, I'll take a look.
