### ISSUE TITLE
Question about Properties() support

### ISSUE THREAD

**Issue by MSchouwPablo** [ekristen/aws-nuke#295]
Hi!

I'm back again :) 

I was working on support for tags for Pipes & Cognito Userpools, Pipes works and is tested, but I'm having some more issues with the Coginto Userpools. [Link](https://github.com/MSchouwPablo/aws-nuke/tree/cognito-pipes-tags)
Two questions: 
1. I'm able to fetch the tags for the userpools, is the way I implemented still the preferred way (with fetching the accountID through `stsiface.STSAPI` etc
2. I'm not seeing any tags in the output, while I do see them for Pipes for example. Any idea why the Properties() function is not behaving as expected? 
```
eu-west-1 - CognitoUserPool - [] - would remove
eu-west-1 - CognitoUserPool - [] - would remove
eu-west-1 - CognitoUserPool - [] - would remove
eu-west-1 - CognitoUserPool - [] - would remove
Scan complete: 86 total, 86 nukeable, 0 filtered.
```

Thanks!

**Comment by ekristen** [comment]
`types.NewPropertiesFromStruct` only works when fields are exported (capitalized first letters).

**Comment by MSchouwPablo** [comment]
haha i knew that 🤦
