### ISSUE TITLE
Add Route53 Zone tags to Zone Records

### ISSUE THREAD

**Issue by ekristen** [ekristen/aws-nuke#297]
Records can't have tags, but some of those tags from the zone could be valuable information for filtering. We should add zone tags to the zone records. 

              Oh interesting. Technically we could probably do that, pull some of the zone information into the record set (like tags).  Something like `tag:zone:<key>=<value>` that way you could do a filter on a tag of a zone for a record. If you are interested in that we can make a feature request for it. Seems valuable.

_Originally posted by @ekristen in https://github.com/ekristen/aws-nuke/issues/293#issuecomment-2346822362_

**Comment by mdgm88** [comment]
There are other services that this kind of thing could be handy for too e.g. SNS Subscriptions don't have tags, but SNS topics do (also if SNS subscriptions are not attached to a topic it would be nice to be able to delete those).
