### ISSUE TITLE
Tags in ECSCluster, RDSInstance, RDSDBCluster

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#306]
Nuke doesn't see tags in `ECSCluster` and `RDSInstance`. I think the same is happening with `RDSDBCluster` but didn't get a chance to verify it.

**Comment by YuriGal** [comment]
Addition to this (posting it here because it related to RDS stuff): NeptuneCluster and NeptuneInstance don't seem to be query tags.

**Comment by adrianbartnik** [comment]
Is this really resolved? I have the following cluster:

![Image](https://github.com/user-attachments/assets/862463b3-dcb0-4330-b08d-eaea7aff6f0f) that would still be deleted, even though I have configured tags and also the same tags prevent deletion for all other resourcse.

**Comment by ekristen** [comment]
@adrianbartnik if you do not think it is, please open a new issue, include aws-nuke version, your configuration and your logs (ideally in debug mode)

**Comment by adrianbartnik** [comment]
@ekristen: I have found the issue and directly opened a PR to fix it. Thanks a lot for all your work on this project 🙏
