### ISSUE TITLE
shell completion support

### ISSUE THREAD

**Issue by chenrui333** [ekristen/aws-nuke#307]
👋 `rebuy-de/aws-nuke` used to have out of the box shell completion support from cobra, any chance to support shell completion with this project as well? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/190893

**Comment by cloudsurf-digital** [comment]
@ekristen, when's the release available as brew tap? Latest is still 3.21.0 - Thanks in advance!

**Comment by ekristen** [comment]
@cloudsurf-digital it's at ekristen/homebrew-tap now. typically it should be there 1-2 hours automatically after the announcement here, but the action was broken because homebrew changed style rules.
