### ISSUE TITLE
Profile flag not supported in brew installed binary

### ISSUE THREAD

**Issue by cisopaul** [ekristen/aws-nuke#333]
Installed aws-nuke via the homebrew tap per documentation.

`brew install ekristen/tap/aws-nuke`

I have a profile setup in ~/.aws/config which is using AWS SSO profiles. Run the aws-nuke command which chucks the following error:

```
> aws-nuke -profile profileName nuke -c ./new-config.yaml
Incorrect Usage: flag provided but not defined: -profile

```
This happens with -profile (which is in the error message for both) & --profile (which is in the docs)
```
> aws-nuke --profile profileName nuke -c ./new-config.yaml
Incorrect Usage: flag provided but not defined: -profile

```

**Comment by cisopaul** [comment]
seems to be an issue with the order of commands.

aws-nuke --profile <profileName> command. # doesn't work
aws-nuke command --profile <profileName> . # works

**Comment by ekristen** [comment]
By design, switched libraries for cli of the build in v3. If it used to work in any position previously that was an oversight on the notes to not call that out.

**Comment by cisopaul** [comment]
Ok cool, makes sense. Totally happy to close this issue off. Thanks for the swift response

**Comment by ekristen** [comment]
Sounds good. I'll try and put a note in the upgrade guide soon. Thanks!
