### ISSUE TITLE
[resource] opensearch serverless collections

### ISSUE THREAD

**Issue by ekristen** [ekristen/aws-nuke#344]
https://github.com/rebuy-de/aws-nuke/issues/1215

**Comment by deekayw0n** [comment]
Hia @ekristen not sure how much effort this one would be, but would also be thrilled to see opensearch service resources destroyed...I have a global team that is constantly experimenting with this and I miss manually deleting, leading to repeat, persistent flat costs that I need to track down across the aws footprint.  Thanks kindly for your time and dedication!
