### ISSUE TITLE
Do not delete KMS keys by alias

### ISSUE THREAD

**Issue by moltar** [ekristen/aws-nuke#367]
It is possible to specify a filter like this:

```yaml
      KMSAlias:
        - alias/cdk-hnb659fds-assets-key
```

But the underlying key that alias points to, still gets deleted.

```
ap-northeast-1 - KMSKey - c38c7e34-**** - [ID: "c38c7e34-****", Manager: "CUSTOMER", State: "Enabled"] - would remove
```

---

![screenshot-20241005T202858-JuzqZwir@2x](https://github.com/user-attachments/assets/e8ae2c02-07c4-4b88-8ef6-7f3d8067369c)

**Comment by ekristen** [comment]
Unfortunately it is not at this time. AWS treats KMS Aliases as entirely separate resource. We might be able to modify the behavior to include the first found alias maybe, but only if that's deterministic. Technically a key can have multiple aliases.

**Comment by ekristen** [comment]
#375 implements a fix, but you'll have to change a configuration ...

```yaml
KMSKey:
  - property: Alias
    value: alias/cdk-hnb659fds-assets-key
```

**Comment by moltar** [comment]
Thank you 🙏

**Comment by ekristen** [comment]
@moltar You can test it from the builds here - https://github.com/ekristen/aws-nuke/actions/runs/11294170251
