### ISSUE TITLE
Request: support for logical "and" for filters

### ISSUE THREAD

**Issue by vorezal** [ekristen/aws-nuke#378]
I have a case where our infrastructure is not well suited to writing exclusion rules using only a single tag or property. It would be really helpful to have the ability to exclude resources where multiple conditions are true.

Considering the text in config-filtering.md this is definitely a known limitation and there may not be an easy solution, but it would be extremely useful. Perhaps a new filter type that allows multiple standard filters to be nested?

**Comment by ekristen** [comment]
I'm working on a feature called Filter Groups, it'll essentially allow you to do groups of filters on a resource, each group will be AND, each filter within a group will be OR together.

**Comment by vorezal** [comment]
Awesome! I saw that feature called out but wasn't sure quite what they would do. Much appreciated!

**Comment by vorezal** [comment]
I finally was able to get this tested for our use case. Unfortunately, if I am reading things correctly it isn't the best fit for us. I'd be interested in your take on solutions using this feature for our case however.

We would like to exclude most of our resources based on the default behavior since that is how we have already written our configurations based on previous logic. We would like to then filter certain resources out with a logical AND using multiple tags, but without impacting the default exclusions. As an example based on the documentation:

filters:
  ResourceType:
    - property: Name
      value: SomeResource
    - property: tag:env
      value: dev
      group: group1
    - property: tag:namespace
      value: test
      group: group2

Correct me if I'm wrong, but since resources belong to a default group by, well, default, this would result in SomeResource only being excluded if it also had the group1 and group2 tags, which also seems to limit AND groups to be global per resource. We would want SomeResource excluded, OR anything with group1 AND group2 tags excluded.

Perhaps this logic may not even be feasible as aws-nuke is currently written. Maybe we will need to split out our config files into separate ones for each logical AND combination we want to support. Open to thoughts though. Selfishly, I think I would have wanted a feature with logic like "exclude everything in the default group OR exclude everything in group1 ANDed together OR exclude everything in group2 ANDed together" etc. But I could easily be thinking about his completely wrong.

**Comment by ekristen** [comment]
Unfortunately, that logic is too complicated at this point. Based on how the original tool was written with a filter logic this was the best I could do to get some additional control in the short term.

I would have to introduce another layer on top of it to control specific groups being ORd or ANDd.

**Comment by vorezal** [comment]
I figured that would probably be the case. Well, if it ever appears as a feature I'll be happily surprised. Just having the tool maintained and updated is really great though. Thank you for taking it on and putting in so much work!

**Comment by ekristen** [comment]
If you'd like to open a feature request, then people can vote and I'll give some thought on how it could be implemented, for now my focus is stability and upgrading the AWS SDK.
