### ISSUE TITLE
[BUG] aws-nuke failures on 3.28.0 and 3.29.0

### ISSUE THREAD

**Issue by mdgm88** [ekristen/aws-nuke#392]
On 3.28.0 aws-nuke failed with the error
`time="2024-10-18T10:03:06Z" level=fatal msg="*resources.CloudWatchEventsTarget does not support custom properties"`

and on 3.29.0 aws-nuke failed with the error
`time="2024-10-19T10:03:02Z" level=fatal msg="*resources.BackupVaultAccessPolicy does not support custom properties"`

These errors were warnings not fatal on 3.27.0 and earlier. So something has changed since that release.

**Comment by ekristen** [comment]
Interesting, I'll take a look right away.

**Comment by ekristen** [comment]
This was an inadvertent bug introduced when I was finishing up the filter group feature which is currently behind a feature flag inside of aws-nuke. It was introduced in libnuke@0.21.0. 

This PR https://github.com/ekristen/libnuke/pull/81 and subsequent release of libnuke has the fix, it'll land in aws-nuke shortly. https://github.com/ekristen/libnuke/releases/tag/v0.21.1
