### ISSUE TITLE
Show dependencies.

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#394]
If I target an individual resource type in the nuke config (e.g. IAM role), and removal fails - is there a way to find the reason (e.g. what resource depends on this role)?

**Comment by ekristen** [comment]
Not with aws-nuke, at best it'll give you the failure reason provided by the API at the end of the run. The AWS Console typically will delete or inform you of the dependents depending on the resource that is. For example, with VPCs in the console, it'll delete some resources automatically, other's it'll prompt you about and you have to cleanup on your own.

**Comment by YuriGal** [comment]
Got it. We have, maybe, an edge case, there is an account that is used as a dev playground, and it has huge amount of old stale resources. If we run nuke without specifying resource types - even dry run takes many hours, and we have to interrupt it. If we target a specific resource type - dry run finished pretty quickly, but actual deletion fails, because of dependencies on resources whose type is not included into config. Looking for the best way to proceed.

**Comment by ekristen** [comment]
You might be best using a too like cloudquery.io to get a full inventory and picture of that AWS account, that should help you craft some configurations.
