### ISSUE TITLE
Does this support breaking down and closing AWS Organizations member accounts?

### ISSUE THREAD

**Issue by swirle13** [ekristen/aws-nuke#396]
I have a customer who is looking to tear down and fully close out a handful of aws accounts, all of which are members of an AWS Organization as "member accounts".

From what I read on the AWS docs, infrastructure is not required to be torn down before closing an account and will not be billed except in a few special circumstances (e.g. AWS marketplace subscriptions, Savings Plans, and Reserved Instances) ([docs here](https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-closing.html#close-account-considerations)).

I think the only issue would be ensuring each member account has the proper role in it (default when creating AWS Organization member account directly is `OrganizationAccountAccessRole`, otherwise is a custom name if an account was created outside the AWS Organization and invited in) and the role/user used to invoke aws-nuke has the proper IAM permissions, e.g. `sts:AssumeRole` on all of the member account IDs in the AWS Organization.

This seems like it could be an outer layer of looping through and invoking aws-nuke logic in each account.

Is this something that aws-nuke supports or would be in-scope for future support? Thank you

**Comment by ekristen** [comment]
You can use assume role already via the cli to run against accounts, and yes the role has to pre exist.

Otherwise you could create a unique IAM user in the account to be torn down run the tool and then manually remove the user.

In either case it's a good use case to delete most everything.

**Comment by swirle13** [comment]
I appreciate your response, that was helpful, thank you
