### ISSUE TITLE
Wrong identificaion?

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#403]
I've created following resources

- Neptune cluster `nuke-neptune`
- Neptune instance `nuke-neptune-instance-1`
- RDS cluster - `nuke-database`
- RDS instance - `nuke-database-instance-1`

When the nuke runs - I see following output:

```
us-west-2 - RDSDBCluster - nuke-database - would remove
us-west-2 - RDSDBCluster - nuke-neptune - would remove
us-west-2 - NeptuneCluster - nuke-database - would remove
us-west-2 - NeptuneCluster - nuke-neptune - would remove
us-west-2 - RDSInstance - nuke-database-instance-1 - would remove
us-west-2 - RDSInstance - nuke-neptune-instance-1 - would remove
us-west-2 - NeptuneInstance - nuke-neptune-instance-1 - would remove
```

Looks like it's listing RDS resources as Neptune resources as well. Is it supposed to do this?

**Comment by YuriGal** [comment]
Just got the latest one 3.29.1

**Comment by ekristen** [comment]
Ok. Looks like Neptune instance is good, need to do filtering on cluster and RDS instance.
