### ISSUE TITLE
EKS Fargate Profiles Not Being Filtered Correctly

### ISSUE THREAD

**Issue by jordanc99** [ekristen/aws-nuke#405]
I am experiencing an issue with EKS Fargate Profiles not being filtered as expected. These profiles are tagged resources with multiple tags, but it seems that Nuke is not reading them correctly. Below is an example of the dry run output:

`eu-central-1 - EKSFargateProfile - #### - [Cluster: "###", Profile: "###"] - would remove`

One of the tags attached to these profiles is “DoNotNuke - True”. This tag appears in the dry run output for all my other resources, but not for the EKS Fargate Profiles.

**Comment by ekristen** [comment]
@jordanc99 not all resources support properties or include tags by default. In this case, properties are supported, but tags are not being queried for and are not being added, therefore you cannot filter on tags.

**Comment by ekristen** [comment]
@jordanc99 please test with the latest version of aws-nuke, it appears that we are fetching tag data. This was added in 3.25.0 via https://github.com/ekristen/aws-nuke/pull/329
