### ISSUE TITLE
EFS filesystems are not cleaned up

### ISSUE THREAD

**Issue by ikarlashov** [ekristen/aws-nuke#407]
Hi

We use aws-nuke v3.24.0. We have 20+ filesystems and each one has 3 mount targets.

Our EFS are not cleaned up. There're not so many logs related to EFS, the one that is relevant is:

```
time="2024-11-05T23:03:02Z" level=error msg="Listing EFSFileSystem failed:\n    ThrottlingException: Rate exceeded\n    {\n      RespMetadata: {\n        StatusCode: 400,\n        RequestID: \"86478f25-8d71-45ee-8987-d0953a16c006\"\n      },\n      Message_: \"Rate exceeded\"\n    }" error="ThrottlingException: Rate exceeded\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"86478f25-8d71-45ee-8987-d0953a16c006\"\n  },\n  Message_: \"Rate exceeded\"\n}"
```
I couldn't track it down in CloudTrail tho. 

I do see that EFS Mount Targets are removed for each filesystem, so I don't think it's blocking EFS from removal.

Please let me know if any additional information is required.

**Comment by ekristen** [comment]
@ikarlashov please know that 3.24.0 is several revisions behind, I always suggest testing the latest. With that in mind, it looks like I need to add a rate limit check to EFS Filesystem.

**Comment by ekristen** [comment]
Doesn't look like AWS publishes any quota for the API :/ @ikarlashov if you get any sense or can ask your support what the rate limiting on Describing EFS Filesystems that would help.

**Comment by ikarlashov** [comment]
I asked AWS about the limit that they have for EFS. Unfortunately they didn't respond with numbers. Although, they increased a quota :-/

**Comment by ekristen** [comment]
@ikarlashov I did some testing and it looks like 10 RPS might be the magic number, I have #429 building via https://github.com/ekristen/aws-nuke/actions/runs/11979981367 if you can snag the binaries from there after it's done and test it I would appreciate it.

**Comment by ekristen** [comment]
@ikarlashov when you get some time, could you please try and test this feature out. Thank you!

**Comment by merusso** [comment]
@ekristen, I'm running into this error on the latest version of aws-nuke.

```
aws-nuke - v3.52.1 - f5e14a824bf4f8ed31dfa881b2a2805f3a9c9b25
no-prompt flag set, continuing without prompting user
waiting 3s before continuing
starting scan for resources
time="2025-05-02T17:32:23-05:00" level=error msg="listing failed:\n    ThrottlingException: Rate exceeded\n    {\n      RespMetadata: {\n        StatusCode: 400,\n        RequestID: \"9b95b3e0-a3ef-4168-8537-95dc6cfdb077\"\n      },\n      Message_: \"Rate exceeded\"\n    }" error="ThrottlingException: Rate exceeded\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"9b95b3e0-a3ef-4168-8537-95dc6cfdb077\"\n  },\n  Message_: \"Rate exceeded\"\n}" owner=us-west-2 resource_type=EFSFileSystem
Scan complete: 0 total, 0 nukeable, 0 filtered.
```

AWS docs say the following about this rate limit ([source](https://docs.aws.amazon.com/efs/latest/ug/api-reference.html#api-throttling)):
> Amazon EFS API requests are throttled for each AWS account on a per-region basis to help service performance. All Amazon EFS API calls together, whether they originate from an application, the AWS CLI, or the Amazon EFS console, must not exceed the maximum allowed API request rate. The maximum API request rate can vary across AWS Regions. API requests made are attributed to the underlying AWS account.
> 
> If an API request exceeds the API request rate for its category, the request returns the ThrottlingException error code. To prevent this error, ensure that your application doesn't retry API requests at a high rate. You can do this by using care when polling and by using exponential backoff retries.

Given this behavior, I don't think you'll be able to avoid hitting the rate limit for this client, since the rate limit is applied to all calls from the account. What if this call used retries with exponential backoff instead?

**Comment by jjchambl** [comment]
Looking at the rate limit [configuration](https://github.com/ekristen/aws-nuke/blob/main/resources/efs-filesystem.go#L37) for efs filesystems, it seems like the 10 RPS setting is a best guess on the max supported by aws. Could this be made configurable, or otherwise a slightly lower value? On larger clusters/with more users there's a possibility that other API calls are occurring at the same time as this command, which makes rate limiting more likely.

**Comment by ekristen** [comment]
It is best guess. Yes @jjchambl I think I need to take some time to figure out the best way to expose these as settings that can be tweaked.
