### ISSUE TITLE
Multi-region custom KMS Keys and deletion

### ISSUE THREAD

**Issue by bdellegrazie** [ekristen/aws-nuke#408]
Hi,

It appears that aws-nuke is retries deleting the primary key of a custom multi-region KMS key even though it's already marked for deletion.

The code here:
https://github.com/ekristen/aws-nuke/blob/1ba4abc51992dd645ff7209926b9f67d44facb36/resources/kms-key.go#L137

Correctly handles a key with state `KeyStatePendingDeletion` but a multi-region key has state `KeyStatePendingReplicaDeletion`.
I think if this is turned into an _or_ condition things will work as intended.

I will have a try at a PR as it looks like a pretty trivial change.

Thanks!

**Comment by ekristen** [comment]
Thanks for the issue and the PR, I made one comment, once that's taken care of we'll get his merged and a new build will be cut automatically!
