### ISSUE TITLE
Consistent Service output information

### ISSUE THREAD

**Issue by bigjimmynz** [ekristen/aws-nuke#416]
In usage of the tool I've noticed that not all services return the same amount of information. I've been testing a process that converts the output to csv or even xlsx for reporting. 

Some services don't return the same amount of info, so don't allow for the same delimiters. Which means conversion to a columnar format for reporting doesn't work. 

For Example:
IAM Role output (5 "columns"):
global - IAMRole - CloudSecAuditRole - [CreateDate: "2024-07-01T15:26:50Z", LastUsedDate: "2024-07-01T15:26:50Z", Name: "CloudSecAuditRole", Path: "/"] - filtered by config
CodeCommit output (4 "columns"):
ap-southeast-2 - CodeCommitRepository - saas_provisioning - would remove

Does anyone else have a similar need?

I'm happy to attempt to work on it.

**Comment by ekristen** [comment]
There is a PR in progress for structured logging, that'll end up being the best option once it's finalized. https://github.com/ekristen/aws-nuke/pull/368

**Comment by bigjimmynz** [comment]
Great, thank you. Will keep an eye on that.
