### ISSUE TITLE
Nuke stalls

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#426]
We have an account in a desperate need for cleanup, it's been used as playground, have tons of old stale resources. When I run nuke on this account - the nuke just stalls, not outputting anything even a list of would be removed resources. Any idea what's causing it?

**Comment by YuriGal** [comment]
My theory it hits a resource type with huge number of resources, and just gets stuck on it. If so - can I bypass it somehow (I know I can add it to the exclusion list, but I will have to guess which resource type it is every time it happens). And also - how do I actually clean up these resources?

**Comment by YuriGal** [comment]
Yes, matter of fact I tried to target exclusively `CloudWatchLogsLogGroup`, but this account has 34K of those.

**Comment by ekristen** [comment]
Well this gives us a place to start ... 

Unfortunately 34k is a LOT and there are rate limits involved with those APIs. 

We can only query 10 queries per second, 50 at a time at a time, then 15 streams queries per-second.

https://github.com/ekristen/aws-nuke/blob/main/resources/cloudwatchlogs-loggroups.go#L44-L49

34k at 50 per query is 680 queries to describe log groups. Because we also query LogStream to get some additional metadata, there's 1 query per log group 15 per second max, so that's 34k at 15/second - that's 37 minutes to discover.

I can add some debugging logging to a special build for testing via github actions. It's likely just taking forever to query everything.

It's possible I could add a setting to bypass querying the log stream, that'd cut out 37 minutes worth of time.

**Comment by YuriGal** [comment]
It's not just log groups, there are other resource types with huge number of resources. Would it be possible to add a generic option to limit number of resources nuke enumerates per resource type, something like `--max-resources 5000` so it won't have to enumerate everything?

**Comment by ekristen** [comment]
Interesting idea. What do you think would be more useful, per resource or global.

```--max-per-resource-type=50``` would limit to top 50 of each resource type.

```--max-resources=5000``` would limit to the first 5000 discovered (this might be harder to implement)

**Comment by YuriGal** [comment]
I think per resource type is a better option. Nuke has no problems going over large number of resource types, it's when a particular resource type has huge number of resources - it gets stuck. Limiting number of resources retrieved per resource type should solve this issue.

**Comment by ekristen** [comment]
My only wonder if it should be per-resource type instead of globally for all resource-types. Like `--max-per-resource-type resourcetype=blah`

**Comment by YuriGal** [comment]
Having option per specific resource type is good if you know the resource type that causing troubles - then you can target that type specifically. But sometimes you don't know in advance which type it's going to be. If it's possible to have it both ways (if type is specified - apply limit only to that type, otherwise to all types) it would be the best of both worlds.

**Comment by mdgm88** [comment]
You would need to run aws-nuke a lot more times to clean everything up with this limit in place, but at least it wouldn't get stuck.

If aws-nuke is run regularly against an account it should work well most of the time.

Cost Explorer can help identify where the spend is in an account but that doesn't necessarily correspond to what you have a lot of. You can have a huge amount of something that costs a negligible amount, and not much of something that costs a lot.

**Comment by ekristen** [comment]
It definitely feels like an advanced feature. It's something that would have to be implemented per resource too.

**Comment by YuriGal** [comment]
> If aws-nuke is run regularly against an account it should work well most of the time.

That's the idea. It's the initial cleanup that is problematic, once it's done we plan to schedule a weekly nuke run that should keep things tidy. We already do this with our other sandbox accounts, and it works pretty well.
 
> Cost Explorer can help identify where the spend is in an account but that doesn't necessarily correspond to what you have a lot of. You can have a huge amount of something that costs a negligible amount, and not much of something that costs a lot.

Same, e.g. we have thousands of log groups that are over 5 years old, and contain literally gigabytes of logs.

**Comment by ekristen** [comment]
@YuriGal this is not hard to implement but very time consuming and beyond this use case I'm not sure it makes sense to do just yet. However, I'd be willing to create a branch, make a hard coded change on the 1 or 2 resources you are having issues with and I can upload a release against the issue, or you can build the docker image yourself with the changes. What do you think?

**Comment by ygalanter** [comment]
If I can get a Darwin ARM binary for the release that has this feature for CloudWatch log groups and Quicksight users - it would be of a great help!

**Comment by YuriGal** [comment]
If I can get a Darwin ARM binary for a release that would have this feature for Cloudwatch log groups, and Quicksight users - it would be a great help, thanks!

**Comment by ekristen** [comment]
It would be custom so not an actual release. Just a custom branch, I can build it for you and post a link to download.

**Comment by YuriGal** [comment]
Oh yes, I understand, I didn't mean it would be a general release. And I really appreciate you doing this.

**Comment by ekristen** [comment]
https://github.com/ekristen/aws-nuke/actions/runs/12130672455/artifacts/2264757595

**Comment by ekristen** [comment]
@YuriGal builds are at the above link, let me know how it goes. Wish you luck.

**Comment by YuriGal** [comment]
Thanks! What is the name of the flag you implemented? It doesn't seem to recognize `--max-per-resource-type`

**Comment by ekristen** [comment]
No flag. I just hard coded for 1000 max per run.

**Comment by YuriGal** [comment]
I am getting error
```
FATA[0120] failed get caller identity: RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": dial tcp: lookup sts.amazonaws.com: i/o timeout 
```
I am running commands under `aws-vault`, and released nuke doesn't have this issue.

**Comment by ekristen** [comment]
I just tested on two different machines. Works ok.

**Comment by YuriGal** [comment]
Weird. How are you supplying AWS credentials?

**Comment by ekristen** [comment]
Always environment variables. :) 

i/o timeout indicates to me that the local system is preventing the network connection for whatever reason

**Comment by ekristen** [comment]
That's it. I think I have it setup to only sign tagged builds. System Preferences > Security you can hit allow to run, that should fix things.

**Comment by YuriGal** [comment]
That's the thing - I did that, and it allowed me to run this build. But apparently it doesn't allow it to connect.

**Comment by YuriGal** [comment]
Sorry, still unable to run it. I enabled it in security settings, so I can execute it. I added it to firewall allowed list, but still I am getting
```
FATA[0120] failed get caller identity: RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": dial tcp: lookup sts.amazonaws.com: i/o timeout 
```
when running it. Just to reiterate this does not happen with released nuke version

**Comment by ekristen** [comment]
@YuriGal fixed the signing -- https://github.com/ekristen/aws-nuke/actions/runs/12189713328/artifacts/2282303070

**Comment by adamLShine** [comment]
Hi All, 

I believe I may also having this issue, I have approx 2400 resources in my AWS account and AWS Nuke is flagging 1800 resources to be removed. My pipeline running AWS nuke has been running for 75 minutes, does that seem too long for that amount of resources?

**Comment by ekristen** [comment]
Yuris problem is different likely.

 
What resource types? How far does it get? Send logs and config.

**Comment by adamLShine** [comment]
Here is a copy of my config file, I have 6000 log groups and when I run aws nuke within my pipeline it just stalls. I have had it running for 30+ minutes (see screenshot)

`
regions:
  - global
  - us-east-1
  - ap-southeast-2

bypass-alias-check-accounts:
  - "111111111111"

accounts:
  111111111111: # Sandpit

resource-types:
  includes:
    - CloudWatchLogsLogGroup
`

<img width="818" alt="Screenshot 2024-12-09 at 11 48 24 PM" src="https://github.com/user-attachments/assets/bd95120d-e6e6-4759-84de-9eaedece3263">

**Comment by ekristen** [comment]
oh, you probably want to try and use the binaries I built for this, it limits it to 1000 each run and strips a bunch of extra queries out. Just to get you a decent baseline.

**Comment by adamLShine** [comment]
ok thanks, I'm using the docker images are the binaries included on them or will they need to be added separately?

**Comment by ekristen** [comment]
You'll need to grab them from the GitHub Actions, this is a special build to try and help you all out for the time being while I think through if I can easily implement a limits cli option.

**Comment by adamLShine** [comment]
Thanks! That definitely helped and it's no longer stalling for my Cloudwatch log groups

However if I remove the 'resources types' from my config file and run again aws nuke stalls again. From my testing is seems like aws nuke has a difficult time running over a large aws account without stalling.

<img width="768" alt="Screenshot 2024-12-10 at 10 55 02 AM" src="https://github.com/user-attachments/assets/b161fc70-b467-448f-909b-7952ecb8543e">

**Comment by ekristen** [comment]
That message is normal. Do you have S3Object excluded? 

Open a new issue about this please, provide version and config and run with log level trace and provide that.

**Comment by adamLShine** [comment]
Thanks, yes I do. The new issue is here https://github.com/ekristen/aws-nuke/issues/453

**Comment by YuriGal** [comment]
> @YuriGal fixed the signing -- https://github.com/ekristen/aws-nuke/actions/runs/12189713328/artifacts/2282303070

Thanks! Finally managed to run it. Just to confirm - hard-coded 1000 resources limit applies only to Quicksight users and Cloudwatch log groups, or to all resource types in the account?

**Comment by ekristen** [comment]
Just to the cloudwatch log groups. We can do more hard coding in a special build if needed to help you out I don't mind, but to do it where it's configurable will take a bit of effort that I don't have time for at the moment.

**Comment by YuriGal** [comment]
I think having Cloudwatch groups support should suffice for us for now, they're the main offender. For the rest I'd rather wait when the feature is officially supported in a release. Thanks again!

**Comment by YuriGal** [comment]
The dev build you provided was very helpful, is there generic support of max item per resource type on the roadmap?

**Comment by ekristen** [comment]
Hi @YuriGal thanks for asking. That's a pretty large lift at the moment and I don't have the time to dedicate to it. I'll create an issue for it and when I can get around to it I will. I always am willing to discuss implementation details if someone else wants to do a PR. However, being fully transparent here, if your organization would like to do a 1 time or recurring sponsorship to prioritize getting that feature in and the work done, I'd be happy to discuss that via email to see what we can work out.
