### ISSUE TITLE
Bedrock Agent Datasource: DELETE_UNSUCCESSFUL when data is already deleted

### ISSUE THREAD

**Issue by npellegrin** [ekristen/aws-nuke#431]
When aws-nuke delete the S3 bucket associated with the Berock datasource before deleting the datasource itself, the datasource cannot be removed. The error message message displayed is:

```
Unable to delete data from vector store for data source with ID ABCDEF. Check your vector store configurations and permissions and retry your request. If the issue persists, consider updating the dataDeletionPolicy of the data source to RETAIN and retry your request.
```

This error can be fixed by updating the datasource before deletion, and setting the data retention policy to RETAIN. This way, AWS will not try to delete the corresponding ghost data, and can delete the datasource properly.

Fixing this bug will have a consequence: deleting a Bedrock datasource, and filtering the S3 buckets from aws-nuke config will retain the data from corresponding S3 bucket datasource.

**Comment by ekristen** [comment]
We do that with cloud formation, I think a PR to always set to retain before deleted is optimal. Then s3 bucket deletion will not have any adverse effect

**Comment by npellegrin** [comment]
Thanks ! The pull Request on the way ✈️ I am fixing the CI lint and it will be ready 😄
