### ISSUE TITLE
External OpenSearch package plugins not whitelisted

### ISSUE THREAD

**Issue by Pati93** [ekristen/aws-nuke#433]
Hey,
Currently only AWS owned packages are whitelisted  ([source](https://github.com/ekristen/aws-nuke/blob/main/resources/opensearchservice-package.go#L77)) from OpenSearch . Recently AWS added some third party packages ([post](https://aws.amazon.com/de/about-aws/whats-new/2024/11/amazon-opensearch-service-new-third-party-plugins/)). These cannot be deleted and should be filtered as well.
Can I create a pull request for it?

**Comment by ekristen** [comment]
Hi @Pati93 pull requests are welcome, but please read the contributing documentation first, it should explain everything. I've had others submitting PR with success.

Have you tested the latest version @Pati93? We did make a recent change to the opensearch packages where we filter out ZIP-PLUGIN now https://sans-enterprise.atlassian.net/jira/servicedesk/projects/CS/queues/custom/1764/CS-138. 

Let me know what you find and again PRs are welcome! Thanks for asking. Looking forward to your contribution.

**Comment by Pati93** [comment]
Hey @ekristen , thanks for your answer! I just upgraded to the latest version and now they are filterted, too. I will close the issue
