### ISSUE TITLE
Allowlist Terms configuration

### ISSUE THREAD

**Issue by bboure** [ekristen/aws-nuke#440]
I have a need for the opposite option to `blocklist-terms`.

When present, `accounts` should become optional and any accounts containing those terms in their alias would be allowed to be nuked.

My use case is that I want to use `aws-nuke` on sandbox accounts. Those accounts would be created programmatically (I'm building an account vending machine), so I don't necessarily want/can update the config file each time a new account is created.

```yaml
allowlist-terms:
  - sandbox
  - ephemeral
```

Thanks.

**Comment by ekristen** [comment]
I've thought about this, I don't think an allow list is a feature I'd be willing to support. However some sort of template system might be. I just see too much risk in allowing this to run against any account id, solely based on terms in the alias.

**Comment by bboure** [comment]
Thanks for the feedback.

Templating is the alternative I had in mind too.  For now, it will do the job.

Thanks again
