### ISSUE TITLE
lister for resource type not found:

### ISSUE THREAD

**Issue by yariv-doit** [ekristen/aws-nuke#450]
I'm getting lots of errors in the log:
level=error msg="lister for resource type not found: RoboMakerDeploymentJob"

this is for the following resources:
AWSBackupVault
ArchiveRule
Budget
EKSFargateProfiles
EKSNodegroups
LaunchConfiguration
LifecycleHook
NetpuneSnapshot
RoboMakerDeploymentJob
RoboMakerFleet
RoboMakerRobot

**Comment by ekristen** [comment]
@yariv-doit please provide aws-nuke version, config, and logs

**Comment by ekristen** [comment]
See `aws-nuke list-resources` for supported resources.

None of those are supported resources.
