### ISSUE TITLE
KMSAlias need to be filtered by tags

### ISSUE THREAD

**Issue by vinhltr** [ekristen/aws-nuke#457]
Currently KMSAlias only has "Name" as its single attribute. It would be very helpful to get all the tag values that it is associated with. This would allow me to use a single "__global__" filter for all resources that I need.

**Comment by ekristen** [comment]
Aliases are their own resource and don't have tags, but I suppose we could pass through the tags from the KMS Key itself, but that would require querying the KMS key as well for every alias. I'll have to think about that a bit.
