### ISSUE TITLE
Shared transit gateways cannot be deleted

### ISSUE THREAD

**Issue by lauraseidler** [ekristen/aws-nuke#458]
Transit gateways that are [shared from other accounts](https://docs.aws.amazon.com/vpc/latest/tgw/working-with-transit-gateways.html#transit-gateway-share) are picked up when listing transit gateways, but then are not found when trying to delete them (which makes sense).

When trying to nuke account `9876543210`:

```
owner - EC2TGW - tgw-000000000000000 - [ID: "tgw-000000000000000", OwnerId: "1234567890"] - failed
time="2024-12-12T04:47:10Z" level=error msg="InvalidTransitGatewayID.NotFound: Transit Gateway tgw-000000000000000 was deleted or does not exist.\n\tstatus code: 400, request id: bc3ae8dc-1974-4c09-899e-507df4bfa41d"
```

We can see that the `OwnerId` does not match the account we're trying to nuke, and we can see in our infrastructure that this matches with transit gateways being shared from other accounts.

I'm not sure if this could/should be handled via Resource Access Manager to remove the share, but for sure deleting them directly will not work - I think it would make sense to skip any TGWs where the owner doesn't match the account being nuked.

**Comment by ekristen** [comment]
@lauraseidler agreed. I haven't had time to sit down to replicate this issue, it's been mentioned in the past. Perhaps a simple check against ownerId would be sufficient. Thanks for the report.

**Comment by lauraseidler** [comment]
@ekristen I also believe the check should be sufficient - we can replicate it quite reliably, so I'll be happy to test a potential fix

**Comment by lauraseidler** [comment]
@ekristen thank you, we'll test it ASAP!
