### ISSUE TITLE
aws-nuke is stuck to 'waiting' when facing deleted EC2TGW

### ISSUE THREAD

**Issue by benriou** [ekristen/aws-nuke#468]
aws-nuke is able to delete an existing TGW but it remains in a 'waiting' state although the object is deleted at the account level

aws-nuke loops on this : 

`us-east-1 - EC2TGW - tgw-0ff0a3932414316f8 - [ID: "tgw-0ff0a3932414316f8", OwnerId: "xxxxxxxxxx", tag:Name: "TGW"] - waiting`

aws-account status : 

![CleanShot 2024-12-20 at 10 51 58@2x](https://github.com/user-attachments/assets/6cc5649c-c01c-49f5-84e0-258f017edaed)

Trace for HTTP transaction with AWS

```

TRAC[0166] sending AWS request:
    > POST / HTTP/1.1
    > Host: ec2.us-east-1.amazonaws.com
    > Authorization: <hidden>
    > Content-Length: 49
    > Content-Type: application/x-www-form-urlencoded; charset=utf-8
    > User-Agent: aws-sdk-go/1.54.20 (go1.21.13; darwin; arm64)
    > X-Amz-Date: 20241220T095415Z
    > X-Amz-Security-Token: <hidden>
    > 
    > Action=DescribeTransitGateways&Version=2016-11-15 
TRAC[0166] received AWS response:
    < HTTP/1.1 200 OK
    < Transfer-Encoding: chunked
    < Cache-Control: no-cache, no-store
    < Content-Type: text/xml;charset=UTF-8
    < Date: Fri, 20 Dec 2024 09:54:15 GMT
    < Server: AmazonEC2
    < Strict-Transport-Security: max-age=31536000; includeSubDomains
    < Vary: accept-encoding
    < X-Amzn-Requestid: e484e32c-174f-475b-a249-774d61ef34e2
    < 
    < 4e8
    < <?xml version="1.0" encoding="UTF-8"?>
    < <DescribeTransitGatewaysResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/"><requestId>e484e32c-174f-475b-a249-774d61ef34e2</requestId><transitGatewaySet><item><creationTime>2024-12-19T18:52:02.000Z</creationTime><description>TGW</description><options><amazonSideAsn>64512</amazonSideAsn><associationDefaultRouteTableId>tgw-rtb-00b4477853d604de6</associationDefaultRouteTableId><autoAcceptSharedAttachments>disable</autoAcceptSharedAttachments><defaultRouteTableAssociation>enable</defaultRouteTableAssociation><defaultRouteTablePropagation>enable</defaultRouteTablePropagation><dnsSupport>enable</dnsSupport><multicastSupport>enable</multicastSupport><propagationDefaultRouteTableId>tgw-rtb-00b4477853d604de6</propagationDefaultRouteTableId><securityGroupReferencingSupport>disable</securityGroupReferencingSupport><vpnEcmpSupport>enable</vpnEcmpSupport></options><ownerId>xxxxx</ownerId><state>deleted</state><tagSet><item><key>Name</key><value>TGW</value></item></tagSet><transitGatewayArn>arn:aws:ec2:us-east-1:xxxxxxx:transit-gateway/tgw-0ff0a3932414316f8</transitGatewayArn><transitGatewayId>tgw-0ff0a3932414316f8</transitGatewayId></item></transitGatewaySet></DescribeTransitGatewaysResponse>

```
we can clearely see : `<state>deleted</state>` that seems ignored by aws-nuke.

**Comment by ekristen** [comment]
What version of aws-nuke are you using?

**Comment by benriou** [comment]
aws-nuke-v3.36.0-linux-amd64.tar.gz

**Comment by ekristen** [comment]
@benriou that's odd, the output should have a state property as well and any state value deleted gets filtered. Can you provide full output?

**Comment by benriou** [comment]
Steps to reproduce 
1- create a TGW
2- start aws-nuke
3- the TGW will be deleted by aws-nuke, is shown as deleted on the AWS interface
4- aws-nuke loops on this object with 'waiting' state

I have the full output in trace mode. 
You can find the TGW named `myTGW` , account number has been obfuscated.

us-east-1 - EC2TGW - tgw-07cb25270da98b350 - [ID: "tgw-07cb25270da98b350", OwnerId: "999999999999", tag:Name: "myTGW"] - waiting


[trace.txt](https://github.com/user-attachments/files/18227776/trace.txt)

**Comment by benriou** [comment]
I can confirm that this issue has been fixed. 
Thank you ! 

```************ - EC2TGW - tgw-03bbc15c833e3358b - [ID: "tgw-03bbc15c833e3358b", OwnerId: "999999999999", State: "available", tag:Name: "testTGW-ben"] - removed```
