### ISSUE TITLE
Latest version has no compiled versions

### ISSUE THREAD

**Issue by fe-ax** [ekristen/aws-nuke#474]
I'm trying to update this to the latest version, but there is no precompiled version this time. I think it is accidental as https://github.com/ekristen/aws-nuke/actions/runs/12472491610 has failed.

Thanks for the work you put in the project! :)

**Comment by ekristen** [comment]
Thanks for the heads up. Hadn't seen the failed notification yet. The issue should be resolved the action is re-running.

**Comment by ekristen** [comment]
It's now published.
