### ISSUE TITLE
Unable to remove "cannot delete default ..." messages using warn or error log level setting

### ISSUE THREAD

**Issue by lestephane** [ekristen/aws-nuke#484]
aws-nuke version v3.31.0

I'm having to add excludes for resource types that cause verbosity that I have no influence over

```
resource-types:
  excludes:
    # --- Remove verbosity from nuke output ---
    - CodePipelineCustomActionType # "cannot delete default codepipeline custom action type"
    - CodeDeployDeploymentConfig # "cannot delete default codedeploy config" 
```

I tried LOGLEVEL warn and error, to no avail. These messages are informational, and pollute the output.

These are just two examples.

**Comment by ekristen** [comment]
You want the quiet switch. --quiet or -q
