### ISSUE TITLE
Filter for all resource types

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#76]
We're tagging all of our resources we want to keep from nuking with a specific tag.

Is it possible to do something like this in the config:
```
presets:
  keep-tag:
    filters:
      *:
        - property: 'tag:nuke.keep'
          value: 'true'
```

**Comment by ekristen** [comment]
I'm actually in the process of writing support for a global filter. Of course it only works if the resource has tags. https://github.com/ekristen/libnuke/pull/37 as soon as I have it completed and tested I'll be doing another beta release and will reference this issue so you can test!

**Comment by ekristen** [comment]
I've merged it into libnuke, but I need to update this tool and write some documentation, I'll try and get to that as soon as I can, but it won't be today.

**Comment by ekristen** [comment]
This is now on the beta.17 release -- https://github.com/ekristen/aws-nuke/pull/77

All feedback and testing would be appreciated. While I've taken great pains to not cause bugs or break things. Take care in testing.

**Comment by YuriGal** [comment]
Will give it a spin, thanks! This should probably reduce size of our config 10 times if not more.

**Comment by ekristen** [comment]
I'm also looking into YAML anchors as anothe way to reduce config sizes and a subcommand to help test configs. Please remember this is beta and feedback is most welcome.

**Comment by ekristen** [comment]
@YuriGal just following up on this. any chance to test?

**Comment by YuriGal** [comment]
Sorry, was diverted to other stuff, will test today!

**Comment by ekristen** [comment]
No worries!

**Comment by ekristen** [comment]
I can definitely add -c back that was an oversight. The assume role should definitely be there. Are you getting an error? 
If you can let me know your exact usage with things sanitized I'll test and get back to you.

**Comment by YuriGal** [comment]
Basically this is our command
```
aws-nuke -c nuke-config.yml --quiet --force --force-sleep 3 --assume-role-arn arn:aws:iam::\<account-id>:role/<role-name> $FLAGS
```
`$FLAGS` is either `--no-dry-run` or unset. This works in the original nuke, in this one it throws 
```
FATA[0000] flag provided but not defined: -assume-role-arn
```
for some reason with one dash.

I just realized - I probably need to use `run` command? Original nuke just accepts parameters.

**Comment by YuriGal** [comment]
Ok, I got past CLI huddles, the command is definitely works. But now I am getting
```
"failed get caller identity: InvalidParameter: 1 validation error(s) found.\n- minimum field size of 2, AssumeRoleInput.ExternalId.\n"
```

**Comment by YuriGal** [comment]
Ok, apparently external ID is needed now, I've added it. Assume role work, but I don't think filter did, unless I am doing this wrong. I have filter set as
```
    filters:
      __global__:
      - property: tag:Baseline"
        value: "true"
```
but in logs I see
```
global - IAMPolicy - arn:aws:iam::xxxxxxxxxxxxxxx:policy/DetectiveInvitationsPolicy - [ARN: "arn:aws:iam::xxxxxxxxxxxxxxxx:policy/XXXXXXXXXXXXXXXXXX", Name: "XXXXXXXXXXXXXXXXX", Path: "/", PolicyID: "XXXXXXXXXXXXXXXXXXX", tag:Baseline: "true"] - would remove
```

**Comment by ekristen** [comment]
@YuriGal thanks for this, I'll test and get back to you ASAP. It should be optional but sounds like there's a logic issue. I have plans to overhaul the AWS in the future, I'm opening issues up and referencing them now.

**Comment by ekristen** [comment]
@YuriGal it looks like your `__global__` has a extra quote `"` on the end of the property based on what you pasted in.

**Comment by YuriGal** [comment]
Damn. Looks like you're right, sorry. I got too reliant on VS Code YAML syntax highlighter, usually it warns about these mismatches, but now it didn't. Will give this another go.

**Comment by YuriGal** [comment]
It works as designed! I will continue to play with this version, but it looks like it's working.

**Comment by ekristen** [comment]
@YuriGal great! FYI `-` hyphen options for long form aren't supported with the CLI library I use, `--` are for long form. `-` are for short form like `-c` that's why the `-assume-role-arn` triggered an error.  I've got https://github.com/ekristen/aws-nuke/pull/80 opened and will be merged soon to address the issues you brought up here.

**Comment by YuriGal** [comment]
Awesome thanks! 

I think I might've discovered another potential problem, this one is about actual run, but I will open a separate issue.

**Comment by YuriGal** [comment]
Woohoo! Thanks!
